apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-production-e2e-pipeline
  labels:
    app: complete-production-e2e-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complete-production-e2e-pipeline
  template:
    metadata:
      labels:
        app: complete-production-e2e-pipeline
    spec:
      containers:
      - name: complete-production-e2e-pipeline
        image: makaraksk/complete-production-e2e-pipeline:1.0.0-61
        ports:
        - containerPort: 8080
        # env:
        # - name: ENV_VAR_NAME
        #   value: "value"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"