apiVersion: v1
kind: Service
metadata:
  name: complete-production-e2e-pipeline-svc
  labels:
    app: complete-production-e2e-pipeline
spec:
  selector:
    app: complete-production-e2e-pipeline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000  # You can specify a custom NodePort (must be in the range 30000-32767)
  type: NodePort
